# Generated by Django 2.0.13 on 2019-05-23 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='出勤場所名')),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='スタッフ名')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='SubmitAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_out', models.CharField(max_length=3, verbose_name='IN/OUT')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='打刻時間')),
                ('place', models.ManyToManyField(max_length=50, to='attendance.Place', verbose_name='出勤場所')),
                ('staff', models.ManyToManyField(to='attendance.Staff', verbose_name='スタッフ')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
