# Generated by Django 2.0.13 on 2019-05-23 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff',
        ),
        migrations.AlterField(
            model_name='submitattendance',
            name='in_out',
            field=models.IntegerField(choices=[(1, 'IN'), (0, 'OUT')], default=None, verbose_name='IN/OUT'),
        ),
        migrations.RemoveField(
            model_name='submitattendance',
            name='place',
        ),
        migrations.AddField(
            model_name='submitattendance',
            name='place',
            field=models.CharField(choices=[('TN', 'TANKS'), ('RT', 'Red Tails'), ('AN', 'ANNIE HALL'), ('NK', 'NOKUROXY'), ('HC', '七'), ('AM', 'ART MON ZEN')], default=None, max_length=50, verbose_name='出勤場所名'),
        ),
        migrations.RemoveField(
            model_name='submitattendance',
            name='staff',
        ),
        migrations.AddField(
            model_name='submitattendance',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='スタッフ'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
