# Generated by Django 2.0.13 on 2019-05-23 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20190523_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='打刻日'),
        ),
    ]
