# Generated by Django 2.0.13 on 2019-05-25 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20190525_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('submitattendance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attendance.SubmitAttendance')),
            ],
            options={
                'db_table': 'fee',
            },
            bases=('attendance.submitattendance',),
        ),
    ]
